# Generated by Django 3.0.8 on 2020-07-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mypost',
            name='upload_user',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
