# Generated by Django 3.0.8 on 2020-07-08 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notebook',
            options={},
        ),
    ]
